### ISSUE TITLE
External antenna on LoRa mini Dev

### ISSUE THREAD

**Issue by DevKumarChandil** [dragino/Lora#5]
I want to use an external antenna for the LoRa in LoRa mini Dev. What are the steps should I follow in order to do so?

**Comment by dragino** [comment]
You can cut the current antenna and connect your antenna to the UF.L connector. 

 

发件人: DevKumarChandil [mailto:notifications@github.com] 
发送时间: 2017年11月20日 14:36
收件人: dragino/Lora
抄送: Subscribed
主题: [dragino/Lora] External antenna on LoRa mini Dev (#5)

 

I want to use an external antenna for the LoRa in LoRa mini Dev. What are the steps should I follow in order to do so?
